/**
 * Precompiles prisma/tenant/migrations/*\/migration.sql into a normal,
 * `import`ed TS module, run at `next build` time (this repo is on disk
 * then, so a plain fs.readFileSync is safe here).
 *
 * Why this exists at all, rather than reading the migrations folder at
 * runtime: Next's build-time file tracer only bundles files reached via a
 * static import or a statically-analyzable require -- a dynamic
 * fs.readFileSync('prisma/tenant/migrations/...') against a path built at
 * runtime is exactly the pattern it's known to prune from a deployed
 * Vercel function. That would work in `next dev` (the whole repo is on
 * disk) and silently 404 in production. Baking the SQL into an imported
 * module sidesteps the tracer entirely -- it's bundled the same way any
 * other code is.
 *
 * The provisioning Server Action (lib/tenantDb/provision.ts, a later
 * phase) runs every {name, sql} here, in order, inside one transaction
 * against a fresh org's own Neon database.
 *
 *   npx tsx scripts/build-tenant-migrations.ts
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = join(__dirname, '..', 'prisma', 'tenant', 'migrations');
const OUT_DIR = join(__dirname, '..', 'lib', 'tenantDb');
const OUT_FILE = join(OUT_DIR, 'migrations.generated.ts');

function main(): void {
  const entries = readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort(); // migration folder names are timestamp-prefixed -- lexical order is chronological order

  if (entries.length === 0) {
    throw new Error(`No migrations found in ${MIGRATIONS_DIR}`);
  }

  const migrations = entries.map((name) => {
    const sql = readFileSync(join(MIGRATIONS_DIR, name, 'migration.sql'), 'utf8');
    return { name, sql };
  });

  const header = `// GENERATED by scripts/build-tenant-migrations.ts from prisma/tenant/migrations/.
// Do not hand-edit -- re-run the script after adding a tenant migration.
`;
  const body = `export interface TenantMigration {
  name: string;
  sql: string;
}

export const TENANT_MIGRATIONS: TenantMigration[] = ${JSON.stringify(migrations, null, 2)};
`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, header + body);
  console.log(`Wrote ${migrations.length} migration(s) to ${OUT_FILE}`);
  for (const m of migrations) console.log(`  - ${m.name}`);
}

main();
